create table if not exists public.workshops (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  organization_number text,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workshop_members (
  workshop_id uuid not null references public.workshops(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner','admin','technician','accounting','viewer')),
  created_at timestamptz not null default now(),
  primary key (workshop_id, user_id)
);

create or replace function public.is_workshop_member(target_workshop uuid)
returns boolean language sql stable security definer set search_path = public
as $$ select exists (
  select 1 from public.workshop_members wm
  where wm.workshop_id = target_workshop and wm.user_id = auth.uid()
) $$;

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  workshop_id uuid not null references public.workshops(id),
  customer_type text not null default 'person' check (customer_type in ('person','company')),
  display_name text not null,
  phone text, email text, address_line text, postal_code text, city text,
  personal_or_org_number text, billing_details jsonb not null default '{}'::jsonb,
  communication_preferences jsonb not null default '{}'::jsonb,
  consent_status text, legacy_name text, needs_review boolean not null default false,
  version integer not null default 1,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id)
);

create table if not exists public.vehicles (
  id uuid primary key default gen_random_uuid(),
  workshop_id uuid not null references public.workshops(id),
  registration_plate text not null, registration_plate_normalized text not null,
  vin text, make text, model text, model_year integer, engine text, fuel_type text,
  raw_description text, version integer not null default 1,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id),
  unique (workshop_id, registration_plate_normalized)
);

create table if not exists public.customer_vehicles (
  id uuid primary key default gen_random_uuid(),
  workshop_id uuid not null references public.workshops(id),
  customer_id uuid not null references public.customers(id),
  vehicle_id uuid not null references public.vehicles(id),
  relationship_type text not null default 'owner', valid_from timestamptz not null default now(),
  valid_to timestamptz, is_primary boolean not null default true,
  unique (customer_id, vehicle_id, valid_from)
);

create table if not exists public.order_statuses (
  code text primary key, name_es text not null, name_sv text not null, sort_order integer not null
);
insert into public.order_statuses(code,name_es,name_sv,sort_order) values
('open','Abierta','Öppen',10),('diagnosis','En diagnóstico','Under diagnos',20),
('waiting_parts','Esperando piezas','Väntar på delar',30),('repair','En reparación','Under reparation',40),
('completed','Terminada','Slutförd',50),('paid','Pagada','Betald',60),
('cancelled','Cancelada','Avbokad',70),('warranty','Garantía','Garanti',80)
on conflict (code) do update set name_es=excluded.name_es,name_sv=excluded.name_sv,sort_order=excluded.sort_order;

create table if not exists public.work_orders (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  order_number bigint generated by default as identity, legacy_order_id text,
  customer_id uuid not null references public.customers(id), vehicle_id uuid not null references public.vehicles(id),
  appointment_id uuid, status_code text not null references public.order_statuses(code) default 'open',
  mileage integer, mileage_raw text, requested_work text,
  customer_name_snapshot text, plate_snapshot text, vehicle_snapshot text,
  opened_at timestamptz not null default now(), completed_at timestamptz, delivered_at timestamptz,
  migration_source text, needs_review boolean not null default false, version integer not null default 1,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id),
  unique (workshop_id, legacy_order_id)
);

create table if not exists public.order_status_history (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  work_order_id uuid not null references public.work_orders(id) on delete cascade,
  from_status text references public.order_statuses(code), to_status text not null references public.order_statuses(code),
  reason text, source text not null default 'application', changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id)
);

create table if not exists public.service_catalog (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  code text, name_es text not null, name_sv text, description text, estimated_minutes integer,
  base_price numeric(12,2), vat_rate numeric(5,2), active boolean not null default true,
  unique(workshop_id, code)
);
create table if not exists public.work_order_services (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  work_order_id uuid not null references public.work_orders(id) on delete cascade,
  service_id uuid references public.service_catalog(id), description text not null,
  status text not null default 'planned', quantity numeric(10,2) not null default 1,
  estimated_minutes integer, actual_minutes integer, unit_price numeric(12,2), vat_rate numeric(5,2),
  sort_order integer not null default 0, technician_id uuid references auth.users(id),
  started_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now()
);

create table if not exists public.suppliers (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  code text, name text not null, organization_number text, phone text, email text, notes text,
  source_type text, active boolean not null default true, unique(workshop_id,name)
);
create table if not exists public.parts (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  internal_number text, oem_number text, description text not null, brand text, unit text not null default 'pcs',
  vat_rate numeric(5,2), barcode text, active boolean not null default true
);
create table if not exists public.supplier_parts (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  supplier_id uuid not null references public.suppliers(id), part_id uuid not null references public.parts(id),
  supplier_part_number text, cost_price numeric(12,2), discount_percent numeric(5,2), availability text,
  last_checked_at timestamptz, unique(supplier_id,part_id,supplier_part_number)
);
create table if not exists public.inventory_locations (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  name text not null, unique(workshop_id,name)
);
create table if not exists public.inventory_items (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  part_id uuid not null references public.parts(id), location_id uuid not null references public.inventory_locations(id),
  quantity numeric(12,3) not null default 0, reserved_quantity numeric(12,3) not null default 0,
  minimum_quantity numeric(12,3), average_cost numeric(12,2), version integer not null default 1,
  unique(part_id,location_id)
);
create table if not exists public.stock_movements (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  part_id uuid not null references public.parts(id), location_id uuid references public.inventory_locations(id),
  work_order_id uuid references public.work_orders(id), supplier_id uuid references public.suppliers(id),
  movement_type text not null, quantity numeric(12,3) not null, unit_cost numeric(12,2), reference text,
  occurred_at timestamptz not null default now(), created_by uuid references auth.users(id)
);
create table if not exists public.work_order_parts (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  work_order_id uuid not null references public.work_orders(id) on delete cascade,
  part_id uuid references public.parts(id), supplier_id uuid references public.suppliers(id),
  part_number_snapshot text, description_snapshot text not null, quantity numeric(12,3) not null default 1,
  actual_cost numeric(12,2), sale_price numeric(12,2), discount_percent numeric(5,2), vat_rate numeric(5,2),
  status text not null default 'quote', stock_movement_id uuid references public.stock_movements(id),
  created_at timestamptz not null default now()
);

create table if not exists public.time_entries (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  work_order_id uuid not null references public.work_orders(id) on delete cascade,
  service_id uuid references public.work_order_services(id), user_id uuid references auth.users(id),
  time_type text not null default 'repair', started_at timestamptz, ended_at timestamptz,
  duration_seconds integer not null default 0 check(duration_seconds>=0), status text not null default 'stopped',
  source text, correction_reason text, version integer not null default 1,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index if not exists one_active_timer_per_user
on public.time_entries(workshop_id,user_id) where status='active';

create table if not exists public.diagnostic_reports (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  work_order_id uuid not null references public.work_orders(id) on delete cascade,
  vehicle_id uuid not null references public.vehicles(id), mileage integer,
  summary text, tests_performed text, findings text, recommended_repair text,
  diagnostic_seconds integer, raw_dtc_text text, created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);
create table if not exists public.diagnostic_dtcs (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  diagnostic_report_id uuid not null references public.diagnostic_reports(id) on delete cascade,
  dtc_code text, raw_code text not null, description_snapshot text, relevance text,
  status text, freeze_frame jsonb not null default '{}'::jsonb, notes text
);

create table if not exists public.appointments (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  customer_id uuid references public.customers(id), vehicle_id uuid references public.vehicles(id),
  work_order_id uuid references public.work_orders(id), starts_at timestamptz not null, ends_at timestamptz,
  reason text, status text not null default 'scheduled', plate_snapshot text, notes text,
  version integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id)
);
alter table public.work_orders drop constraint if exists work_orders_appointment_id_fkey;
alter table public.work_orders add constraint work_orders_appointment_id_fkey foreign key(appointment_id) references public.appointments(id);
create table if not exists public.appointment_status_history (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  appointment_id uuid not null references public.appointments(id) on delete cascade,
  from_status text, to_status text not null, reason text, changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id)
);

create table if not exists public.quotes (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  work_order_id uuid not null references public.work_orders(id), customer_id uuid not null references public.customers(id),
  vehicle_id uuid not null references public.vehicles(id), quote_number bigint generated by default as identity,
  revision integer not null default 1, status text not null default 'draft', subtotal numeric(12,2) not null default 0,
  vat_total numeric(12,2) not null default 0, total numeric(12,2) not null default 0,
  approved_at timestamptz, created_at timestamptz not null default now()
);
create table if not exists public.quote_items (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  quote_id uuid not null references public.quotes(id) on delete cascade, item_type text not null,
  description text not null, quantity numeric(12,3) not null default 1, unit_price numeric(12,2) not null default 0,
  vat_rate numeric(5,2), service_id uuid references public.work_order_services(id), part_line_id uuid references public.work_order_parts(id)
);
create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  work_order_id uuid not null references public.work_orders(id), customer_id uuid not null references public.customers(id),
  vehicle_id uuid not null references public.vehicles(id), invoice_number bigint generated by default as identity,
  status text not null default 'draft', issued_at timestamptz, due_at timestamptz,
  subtotal numeric(12,2) not null default 0, vat_total numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0, fortnox_reference text,
  billing_snapshot jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.invoice_items (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  invoice_id uuid not null references public.invoices(id) on delete cascade, item_type text not null,
  description text not null, quantity numeric(12,3) not null default 1, unit_price numeric(12,2) not null default 0,
  vat_rate numeric(5,2), service_id uuid references public.work_order_services(id), part_line_id uuid references public.work_order_parts(id)
);
create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  invoice_id uuid not null references public.invoices(id), work_order_id uuid not null references public.work_orders(id),
  customer_id uuid not null references public.customers(id), vehicle_id uuid not null references public.vehicles(id),
  method text not null, amount numeric(12,2) not null, status text not null default 'accepted',
  external_reference text, accepted_at timestamptz, receipt_reference text,
  created_by uuid references auth.users(id), created_at timestamptz not null default now()
);

create table if not exists public.warranties (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  original_order_id uuid not null references public.work_orders(id), warranty_order_id uuid references public.work_orders(id),
  vehicle_id uuid not null references public.vehicles(id), service_id uuid references public.work_order_services(id),
  part_line_id uuid references public.work_order_parts(id), reason text not null, status text not null default 'open',
  opened_at timestamptz not null default now(), resolved_at timestamptz, resolution text
);
create table if not exists public.returns (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  work_order_id uuid references public.work_orders(id), customer_id uuid references public.customers(id),
  vehicle_id uuid references public.vehicles(id), supplier_id uuid references public.suppliers(id),
  return_type text not null, reason text not null, status text not null default 'open', amount numeric(12,2),
  created_at timestamptz not null default now(), resolved_at timestamptz
);
create table if not exists public.return_items (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  return_id uuid not null references public.returns(id) on delete cascade,
  part_line_id uuid references public.work_order_parts(id), invoice_item_id uuid references public.invoice_items(id),
  quantity numeric(12,3) not null default 1, amount numeric(12,2)
);
create table if not exists public.notes (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  entity_type text not null, entity_id uuid not null, note_type text, body text not null,
  visibility text not null default 'internal', important boolean not null default false,
  created_by uuid references auth.users(id), created_at timestamptz not null default now()
);
create table if not exists public.attachments (
  id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id),
  entity_type text not null, entity_id uuid not null, storage_bucket text not null, storage_path text not null,
  file_name text not null, mime_type text, size_bytes bigint, created_by uuid references auth.users(id),
  created_at timestamptz not null default now(), unique(storage_bucket,storage_path)
);

create table if not exists public.migration_runs (
  id uuid primary key default gen_random_uuid(), migration_name text not null unique,
  source_key text, source_checksum text, expected_count integer, imported_count integer not null default 0,
  status text not null default 'pending', details jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(), completed_at timestamptz
);
create table if not exists public.legacy_import_records (
  id uuid primary key default gen_random_uuid(), migration_run_id uuid not null references public.migration_runs(id),
  source_key text not null, source_index integer not null, legacy_order_id text,
  raw_payload jsonb not null, payload_md5 text not null,
  customer_id uuid references public.customers(id), vehicle_id uuid references public.vehicles(id),
  work_order_id uuid references public.work_orders(id), status text not null default 'pending',
  error_message text, imported_at timestamptz, unique(migration_run_id,source_index)
);
create table if not exists public.audit_log (
  id bigint generated always as identity primary key, workshop_id uuid,
  table_name text not null, record_id uuid, operation text not null,
  old_data jsonb, new_data jsonb, changed_by uuid, changed_at timestamptz not null default now(),
  correlation_id uuid default gen_random_uuid()
);

create or replace function public.audit_row_change() returns trigger language plpgsql security definer set search_path=public as $$
declare old_row jsonb; new_row jsonb; rid uuid; wid uuid;
begin
  old_row := case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else null end;
  new_row := case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else null end;
  rid := coalesce((new_row->>'id')::uuid,(old_row->>'id')::uuid);
  wid := coalesce((new_row->>'workshop_id')::uuid,(old_row->>'workshop_id')::uuid);
  insert into public.audit_log(workshop_id,table_name,record_id,operation,old_data,new_data,changed_by)
  values(wid,tg_table_name,rid,tg_op,old_row,new_row,auth.uid());
  return coalesce(new,old);
end $$;

do $$ declare t text; begin
  foreach t in array array['customers','vehicles','customer_vehicles','work_orders','order_status_history','work_order_services','work_order_parts','time_entries','diagnostic_reports','diagnostic_dtcs','appointments','quotes','invoices','payments','warranties','returns','notes']
  loop
    execute format('drop trigger if exists audit_%I on public.%I',t,t);
    execute format('create trigger audit_%I after insert or update or delete on public.%I for each row execute function public.audit_row_change()',t,t);
  end loop;
end $$;

do $$ declare t text; begin
  foreach t in array array['workshops','profiles','workshop_members','customers','vehicles','customer_vehicles','work_orders','order_status_history','service_catalog','work_order_services','suppliers','parts','supplier_parts','inventory_locations','inventory_items','stock_movements','work_order_parts','time_entries','diagnostic_reports','diagnostic_dtcs','appointments','appointment_status_history','quotes','quote_items','invoices','invoice_items','payments','warranties','returns','return_items','notes','attachments','audit_log']
  loop execute format('alter table public.%I enable row level security',t); end loop;
end $$;

do $$ declare t text; begin
  foreach t in array array['customers','vehicles','customer_vehicles','work_orders','order_status_history','service_catalog','work_order_services','suppliers','parts','supplier_parts','inventory_locations','inventory_items','stock_movements','work_order_parts','time_entries','diagnostic_reports','diagnostic_dtcs','appointments','appointment_status_history','quotes','quote_items','invoices','invoice_items','payments','warranties','returns','return_items','notes','attachments']
  loop
    execute format('drop policy if exists workshop_member_access on public.%I',t);
    execute format('create policy workshop_member_access on public.%I for all to authenticated using (public.is_workshop_member(workshop_id)) with check (public.is_workshop_member(workshop_id))',t);
  end loop;
end $$;

drop policy if exists workshop_member_read_audit on public.audit_log;
create policy workshop_member_read_audit on public.audit_log for select to authenticated
using (public.is_workshop_member(workshop_id));

insert into public.workshops(name)
select 'Bildiagnos i Utby AB'
where not exists (select 1 from public.workshops where name='Bildiagnos i Utby AB');
insert into public.profiles(id,display_name)
select u.id,coalesce(u.raw_user_meta_data->>'name','Bildiagnos owner')
from auth.users u join public.app_state s on s.updated_by=u.id
where s.key='bildiagnos-orders' on conflict(id) do nothing;
insert into public.workshop_members(workshop_id,user_id,role)
select w.id,s.updated_by,'owner' from public.workshops w cross join public.app_state s
where w.name='Bildiagnos i Utby AB' and s.key='bildiagnos-orders' and s.updated_by is not null
on conflict(workshop_id,user_id) do update set role='owner';

create index if not exists work_orders_vehicle_idx on public.work_orders(vehicle_id,opened_at desc);
create index if not exists work_orders_customer_idx on public.work_orders(customer_id,opened_at desc);
create index if not exists work_orders_status_idx on public.work_orders(workshop_id,status_code);
create index if not exists notes_entity_idx on public.notes(entity_type,entity_id,created_at desc);
